name: Build and Publish a Docker image

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write
      contents: read
      packages: write

    steps:
    - name: Login to GitHub CR
      uses: docker/login-action@v1
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: checkout code
      uses: actions/checkout@v2

    - name: build container  
      run: |
        docker build . --tag "${{ vars.REGISTRY }}/${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:${{ vars.IMAGE_VERSION }}" \
          --tag "${{ vars.REGISTRY }}/${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:$(git rev-parse --short HEAD)"
      
    - name: Scan Image with Grype
      uses: anchore/scan-action@v6
      id: imagescan
      with:
        image: "${{ vars.REGISTRY }}/${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:${{ vars.IMAGE_VERSION }}"
        fail-build: false
        by-cve: true

    - name: Upload Image Scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.imagescan.outputs.sarif }}

    - name: Archive container scan results
      uses: actions/upload-artifact@v4
      with:
        name: grype-scan
        path: ${{ steps.imagescan.outputs.sarif }}

    - name: Publish image
      run: docker push "${{ vars.REGISTRY }}/${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:${{ vars.IMAGE_VERSION }}"
